version: '3.9'

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data/
      - ./db_sql_copy:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      timeout: 2s
      retries: 30

    ports:
      - 5432:5432

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: always

  redis:
    image: redis
    restart: always
    volumes:
    - ./storage/redis/data:/data
    ports:
    - 6379:6379
    depends_on:
      - db
      - elastic
